version: '3.1'

services:

 portainer:
  image: portainer/portainer-ce
  container_name: portainer
  restart: unless-stopped
  environment:
   - TZ=America/Toronto 
  profiles:
   - portainer
   - all
  ports:
   - "9000:9000"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /var/run/docker.sock:/var/run/docker.sock
   - /home/${USERNAME}/portainer:/data

 nginx-proxy-manager:
  image: jc21/nginx-proxy-manager:latest
  container_name: nginx-proxy-manager
  restart: unless-stopped
  environment:
   - TZ=America/Toronto 
  profiles:
   - nginx-proxy-manager
   - all
  ports:
   - "80:80"
   - "81:81"
   - "443:443"
  volumes:
   - /home/${USERNAME}/nginx-proxy-manager/data:/data
   - /home/${USERNAME}/nginx-proxy-manager/letsencrypt:/etc/letsencrypt

 VSFTPd:
  image: fauria/vsftpd
  container_name: vsftpd
  restart: unless-stopped
  environment:
   - TZ=America/Toronto 
   - FTP_USER=${varVSFTPdUser}
   - FTP_PASS=${varVSFTPdPass}
   - LOCAL_UMASK=022
   - PASV_ADDRESS=127.0.0.1
   - PASV_MIN_PORT=31000
   - PASV_MAX_PORT=31010
  profiles:
   - vsftpd
   - all
  ports:
   - "20:20"
   - "21:21"
   - "31000-31010:31000-31010"
  volumes:
   - /home/${USERNAME}/VSFTPd:/home/vsftpd

 wordpress:
  image: wordpress
  restart: unless-stopped
  profiles:
   - wpsite01
   - all
  depends_on:
  - db
  ports:
   - 8888:80
  environment:
   - TZ=America/Toronto
   - WORDPRESS_DB_HOST=db
   - WORDPRESS_DB_USER=${varWORDPRESS_DB_USER}
   - WORDPRESS_DB_PASSWORD=${varWORDPRESS_DB_PASSWORD}
   - WORDPRESS_DB_NAME=wordpress
  volumes:
    - /home/${USERNAME}/wpsite01/wordpress:/var/www/html
    - /home/${USERNAME}/VSFTPd/${varVSFTPdUser}:/var/www/html/quinte
    
 db:
  image: mysql:5.7
  restart: unless-stopped
  profiles:
   - wpsite01
   - all
  environment:
   - MYSQL_DATABASE=wordpress
   - MYSQL_USER=${varWORDPRESS_DB_USER}
   - MYSQL_PASSWORD=${varWORDPRESS_DB_PASSWORD}
   - MYSQL_ROOT_PASSWORD=${varMYSQL_ROOT_PASSWORD}
  volumes:
   - /home/${USERNAME}/wpsite01/mysql:/var/lib/mysql
   - /home/${USERNAME}/wpsite01/mysql_restore/mysql/wordpress.sql:/docker-entrypoint-initdb.d/init.sql

 radarr:
  image: linuxserver/radarr:latest
  restart: unless-stopped
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Toronto 
  profiles:
   - all
   - nzb
  ports:
   - "7878:7878"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/radarr/config:/config
   - /mnt/storage/downloads:/downloads
   - /mnt/videos:/videos

 sonarr:
  image: linuxserver/sonarr:latest
  restart: unless-stopped
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Toronto 
  profiles:
   - all
   - nzb
  ports:
   - "8989:8989"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/sonarr/config:/config
   - /mnt/storage/downloads:/downloads
   - /mnt/videos:/videos

 nzbget:
  image: linuxserver/nzbget:latest
  restart: unless-stopped
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Toronto 
  profiles:
   - all
   - nzb
  ports:
   - "6789:6789"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/nzbget/config:/config
   - /mnt/storage/downloads:/downloads

 tautulli:
  image: tautulli/tautulli:latest
  restart: unless-stopped
  environment:
   - TZ=America/Toronto 
  profiles:
   - all
   - nzb
  ports:
   - "8181:8181"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/tautulli/config:/config

 qbittorrent:
  image: linuxserver/qbittorrent:latest
  restart: unless-stopped
  environment:
   - PUID=1000
   - PGID=1000
   - TZ=America/Toronto
   - WEBUI_PORT=6995
  profiles:
   - all
   - nzb
  ports:
   - "6995:6995"
   - "6881:6881"
   - "6881:6881/udp"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/qbittorrent/config:/config
   - /mnt/storage/torrent/downloads:/downloads 

esphome:
  image: esphome/esphome
  restart: unless-stopped
  environment:
   - ESPHOME_DASHBOARD_USE_PING=true
  profiles:
   - all
   - ha
  ports:
   - "6052:6052"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/esphome:/config

 mosquitto:
  image: eclipse-mosquitto
  restart: unless-stopped
  profiles:
   - all
   - ha
  ports:
   - "1883:1883"
   - "9001:9001"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/mosquitto/config:/mosquitto/config
   - /home/${USERNAME}/mosquitto/log:/mosquitto/log
   - /home/${USERNAME}/mosquitto/data:/mosquitto/data
   
 deconz:
  image: marthoc/deconz:latest
  network_mode: "host"
  devices:
   - /dev/ttyACM0:/dev/ttyACM0
  restart: unless-stopped
  environment:
   - DECONZ_WEB_PORT=8080
   - DECONZ_WS_PORT=8443
  profiles:
   - all
   - ha
  ports:
   - "1883:1883"
   - "9001:9001"
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/deconz:/root/.local/share/dresden-elektronik/deCONZ

 hass:
  image: homeassistant/raspberrypi4-64-homeassistant
  network_mode: "host"
  restart: unless-stopped
  profiles:
   - all
   - ha
  volumes:
   - /etc/localtime:/etc/localtime:ro
   - /home/${USERNAME}/hass/media:/media
   - /home/${USERNAME}/hass:/config
 
